import gleam/list
import gleam/result
import gleam/string

pub const standard_categories = [
  "🌱 Veggie",
  "🥬 Frutas y verduras",
  "🥩 Carne y pescado",
  "🥛 Lácteos y huevos",
  "🥖 Panadería",
  "🥫 Despensa",
  "🍫 Dulces y snacks",
  "🥤 Bebidas",
  "🧊 Congelados",
  "🧼 Limpieza",
  "🧴 Cuidado personal",
  "👶 Bebé",
  "🐾 Mascotas",
  "💊 Farmacia y salud",
  "🏠 Hogar y bazar",
  "📦 Otros",
]

pub fn infer_category(name: String) -> String {
  let lower = string.lowercase(name)

  let rules = [
    #("🌱 Veggie", [
      // Proteínas vegetales
      "tofu",
      "tofu ahumado",
      "tofu firme",
      "tofu sedoso",
      "tempeh",
      "seitan",
      "soja texturizada",
      "proteina texturizada",
      "proteína texturizada",
      "proteina de soja",
      "proteína de soja",
      "edamame",
      "jackfruit",
      "yaca",
      "jaca",
      "heura",
      "quorn",
      "garden gourmet",
      "beyond meat",
      "vegetalia",
      "taifun",
      "soja",
      "soja texturizada",

      // Elaborados tipo falafel
      "falafel",
      "hummus",
      "humus",
      "hummus de remolacha",
      "baba ganoush",
      "tahini",
      "tahin",
      "pasta de sesamo",
      "pasta de sésamo",
      "crema de sesamo",
      "crema de sésamo",
      "harina de garbanzo",
      "masa de garbanzo",
      "aquafaba",

      // Sustitutos de carne y pescado
      "hamburguesa vegetal",
      "hamburguesa vegana",
      "hamburguesa de soja",
      "hamburguesa de lentejas",
      "hamburguesa de garbanzos",
      "hamburguesa de quinoa",
      "burger vegetal",
      "burger vegana",
      "salchicha vegetal",
      "salchichas vegetales",
      "salchicha vegana",
      "salchichas veganas",
      "nuggets vegetales",
      "nuggets veganos",
      "albondigas vegetales",
      "albóndigas vegetales",
      "albondigas veganas",
      "albóndigas veganas",
      "carne vegetal",
      "carne vegana",
      "pollo vegetal",
      "pollo vegano",
      "kebab vegetal",
      "shawarma vegetal",
      "bacon vegetal",
      "beicon vegetal",
      "jamon vegano",
      "jamón vegano",
      "fiambre vegetal",
      "mortadela vegetal",
      "chorizo vegano",
      "chorizo vegetal",
      "atun vegano",
      "atún vegano",
      "gambas veganas",
      "gyozas vegetales",
      "croquetas veganas",
      "rebozado vegano",
      "lonchas veganas",
      "lonchas vegetales",
      "pate vegetal",
      "paté vegetal",
      "pate vegano",
      "paté vegano",
      "pulled vegetal",

      // Sustitutos de lácteos y huevo
      "queso vegano",
      "queso vegetal",
      "queso de anacardo",
      "yogur vegetal",
      "yogur vegano",
      "yogur de soja",
      "yogur de coco",
      "postre de soja",
      "postre vegetal",
      "nata vegetal",
      "mantequilla vegana",
      "mayonesa vegana",
      "huevo vegano",
      "just egg",
      "helado vegano",

      // Ingredientes típicos de cocina vegetariana
      "levadura nutricional",
      "copos de levadura",
      "miso",
      "nori",
      "alga nori",
      "algas",
      "wakame",
      "kombu",
      "spirulina",
      "espirulina",

      // Etiquetas generales
      "vegano",
      "vegana",
      "veganos",
      "veganas",
      "veggie",
      "vegetariano",
      "vegetariana",
      "plant based",
      "plant-based",
    ]),
    #("🧊 Congelados", [
      "helado", "helados", "pizza", "pizzas", "congelad", "hielo", "nugget",
      "nuggets", "croqueta", "croquetas", "guisantes congelados", "sorbete",
      "tarta helada", "empanadilla", "empanadillas", "lasaña", "lasana",
      "San Jacobo", "san jacobo", "varitas", "verdura congelada",
      "patatas congeladas", "patatas fritas congeladas", "rebozados", "gyozas",
      "wok congelado", "masa de pizza", "hojaldre", "calamares", "anillas",
      "palitos de merluza", "pescado congelado", "polo", "polos", "cornetto",
      "tarrina",
    ]),
    #("🧴 Cuidado personal", [
      "champu", "champú", "gel", "pasta de dientes", "dentifrico", "dentífrico",
      "desodorante", "jabon", "jabón", "crema", "toallita", "toallitas",
      "cuchilla", "acondicionador", "colutorio", "hilo dental", "cepillo",
      "cepillo de dientes", "maquinilla", "espuma de afeitar", "afeitar",
      "after shave", "mascarilla", "crema solar", "protector solar",
      "bastoncillos", "algodon", "algodón", "discos desmaquillantes",
      "desmaquillante", "tampones", "tampon", "compresas", "compresa",
      "salvaslip", "copa menstrual", "perfume", "colonia", "laca", "gomina",
      "tinte", "esmalte", "quitaesmalte", "pañuelos", "panuelos", "kleenex",
      "gel de ducha", "gel de baño", "hidratante", "labial", "cacao labios",
      "depilatoria", "cera depilatoria", "preservativo", "preservativos",
    ]),
    #("🧼 Limpieza", [
      "detergente", "suavizante", "lavavajillas", "fairy", "lejia", "lejía",
      "papel higienico", "papel higiénico", "servilleta", "servilletas",
      "bolsa basura", "bolsas basura", "bolsas de basura", "estropajo", "bayeta",
      "limpiacristal", "limpiacristales", "fregasuelo", "fregona", "scrop",
      "papel cocina", "amoniaco", "desengrasante", "antical", "limpiahogar",
      "multiusos", "wc", "pastillas wc", "ambientador", "insecticida", "cubo",
      "escoba", "recogedor", "guantes", "friegaplatos", "quitamanchas", "vanish",
      "ariel", "skip", "perlas", "capsulas", "cápsulas", "sal lavavajillas",
      "abrillantador", "limpiador", "desinfectante", "rollo de cocina",
      "papel de aluminio", "aluminio", "film", "papel film", "papel albal",
      "bolsas de congelar", "papel de horno", "papel vegetal", "fregaplatos",
      "trapo", "mopa",
    ]),
    #("🐾 Mascotas", [
      "pienso", "arena gatos", "arena para gatos", "arena de gato",
      "comida perro", "comida gato", "comida para perros", "comida para gatos",
      "snack perro", "snack gato", "galletas perro", "collar", "correa",
      "antiparasitario", "pipeta", "whiskas", "purina", "pedigree", "friskies",
      "latas gato", "latas perro", "hamster", "pajaros", "pájaros", "alpiste",
      "piedras gato",
    ]),
    #("👶 Bebé", [
      "pañal", "pañales", "panal", "panales", "toallitas bebe", "toallitas bebé",
      "leche infantil", "leche de continuación", "papilla", "papillas", "potito",
      "potitos", "biberon", "biberón", "chupete", "crema pañal", "colonia bebe",
      "colonia bebé", "cereales bebe", "cereales bebé", "tarrito", "tarritos",
    ]),
    #("💊 Farmacia y salud", [
      "ibuprofeno", "paracetamol", "aspirina", "dalsy", "tiritas", "tirita",
      "gasas", "gasa", "esparadrapo", "alcohol", "agua oxigenada", "betadine",
      "termometro", "termómetro", "vitamina", "vitaminas", "magnesio", "omega 3",
      "suplemento", "jarabe", "pastillas garganta", "strepsils",
      "antihistaminico", "antihistamínico", "colirio", "suero", "mascarillas",
      "test covid", "test de embarazo", "pomada", "voltaren", "melatonina",
      "probioticos", "probióticos", "proteina", "proteína", "creatina",
    ]),
    #("🥫 Despensa", [
      "arroz", "pasta", "macarron", "macarrón", "macarrones", "espagueti",
      "espaguetis", "fideo", "fideos", "aceite", "vinagre", "sal", "azucar",
      "azúcar", "cafe", "café", "lenteja", "lentejas", "garbanzo", "garbanzos",
      "alubia", "alubias", "tomate frito", "tomate triturado", "conserva",
      "conservas", "cereal", "cereales", "especias", "pimienta", "oregano",
      "orégano", "mayonesa", "ketchup", "mostaza", "mermelada", "miel",
      "atun lata", "atún lata", "atun en lata", "atún en lata", "caldo",
      "tallarines", "lasaña", "lasana", "tortellini", "ravioli", "noodles",
      "cuscus", "cuscús", "quinoa", "bulgur", "polenta", "sémola", "semola",
      "avena", "copos de avena", "muesli", "granola", "cacao", "colacao",
      "nesquik", "cola cao", "chocolate en polvo", "nutella",
      "crema de cacahuete", "mantequilla de cacahuete", "sirope", "sacarina",
      "edulcorante", "stevia", "levadura", "bicarbonato", "maicena", "gelatina",
      "pure", "puré", "sopa", "sopa de sobre", "gazpacho", "salsa",
      "salsa de tomate", "salsa de soja", "soja", "pesto", "sriracha", "tabasco",
      "alioli", "tomate natural", "pimientos del piquillo", "piquillo",
      "aceitunas", "aceituna", "pepinillos", "encurtidos", "alcaparras",
      "sardinas", "mejillones", "berberechos", "anchoas", "caballa en lata",
      "palmitos", "maiz", "maíz", "maiz dulce", "judias", "judías",
      "garbanzos cocidos", "lentejas cocidas", "legumbre", "legumbres", "fabada",
      "cocido", "aceite de oliva", "aceite de girasol", "aceite girasol",
      "pimenton", "pimentón", "comino", "curry", "canela", "nuez moscada",
      "laurel", "perejil seco", "tomillo", "romero", "ajo en polvo",
      "cebolla en polvo", "azafran", "azafrán", "colorante", "sal gorda",
      "sal fina", "pastillas de caldo", "avecrem", "gallina blanca", "knorr",
      "bechamel", "tomate en polvo", "arroz bomba", "arroz integral", "paella",
      "sofrito", "galletas maria", "pan rallado", "rebozador",
      "tortitas de arroz", "frutos secos", "almendra", "almendras", "nueces",
      "nuez", "cacahuete", "cacahuetes", "pistacho", "pistachos", "anacardo",
      "anacardos", "avellana", "avellanas", "pipas", "pasas", "datiles",
      "dátiles", "ciruelas pasas", "orejones",
    ]),
    #("🥤 Bebidas", [
      "agua", "cerveza", "cervezas", "vino", "zumo", "zumos", "refresco",
      "refrescos", "coca", "pepsi", "fanta", "te", "té", "infusion", "infusión",
      "tonica", "tónica", "gaseosa", "cola", "sprite", "7up", "aquarius",
      "nestea", "red bull", "monster", "bebida energetica", "bebida energética",
      "isotonica", "isotónica", "gatorade", "powerade", "tinto", "blanco",
      "rosado", "cava", "champan", "champán", "sidra", "vermut", "vermú",
      "ginebra", "ron", "vodka", "whisky", "licor", "tequila", "brandy", "coñac",
      "conac", "cerveza sin alcohol", "sangria", "sangría", "tinto de verano",
      "limonada", "horchata", "batido", "bebida vegetal", "leche de almendras",
      "leche de avena", "leche de soja", "leche de coco", "agua con gas",
      "agua mineral", "soda", "kombucha", "mosto", "cafe frio", "café frío",
      "capsulas de cafe", "cápsulas de café", "nespresso", "dolce gusto",
      "manzanilla", "poleo", "tila", "rooibos", "cacao soluble", "mahou",
      "estrella", "damm", "cruzcampo", "heineken", "san miguel",
    ]),
    #("🍫 Dulces y snacks", [
      "chocolate", "chocolatina", "chocolatinas", "bombon", "bombón", "bombones",
      "caramelo", "caramelos", "chicle", "chicles", "gominola", "gominolas",
      "chucheria", "chucherías", "chuches", "patatas fritas", "patatas chips",
      "chips", "ganchitos", "doritos", "pringles", "palomitas", "nachos",
      "tortilla chips", "snack", "snacks", "barrita", "barritas", "galleta",
      "galletas", "oreo", "principe", "príncipe", "digestive", "turron",
      "turrón", "polvorones", "mazapan", "mazapán", "membrillo", "natillas",
      "gelatina postre", "postre", "postres", "tarta", "pastel", "donut",
      "donuts", "napolitana", "palmera", "ensaimada", "cookies", "brownie",
      "kinder", "bueno", "snickers", "twix", "kitkat", "m&m", "lacasitos",
      "regaliz", "piruleta", "pirulis", "cacahuetes fritos", "tostadas dulces",
    ]),
    #("🥛 Lácteos y huevos", [
      "leche", "queso", "yogur", "yogures", "yogurt", "mantequilla", "nata",
      "huevo", "huevos", "mozzarella", "parmesano", "requeson", "requesón",
      "cuajada", "lacteo", "lácteo", "lacteos", "lácteos", "cheddar", "brie",
      "gorgonzola", "flan", "kefir", "kéfir", "skyr", "margarina",
      "queso fresco", "queso rallado", "queso crema", "philadelphia", "burgos",
      "manchego", "cabra", "feta", "halloumi", "emmental", "gouda", "edam",
      "provolone", "ricotta", "mascarpone", "nata para cocinar", "nata montada",
      "leche condensada", "leche evaporada", "leche en polvo", "actimel",
      "danone", "petit suisse", "batido lacteo", "batido lácteo",
      "arroz con leche", "cuajada", "queso en lonchas", "lonchas de queso",
      "sobrasada",
    ]),
    #("🥩 Carne y pescado", [
      "pollo", "ternera", "cerdo", "carne", "pavo", "jamon", "jamón",
      "salchicha", "salchichas", "lomo", "bacon", "beicon", "chuleta",
      "hamburguesa", "pescado", "salmon", "salmón", "atun", "atún", "merluza",
      "gamba", "gambas", "langostino", "langostinos", "bacalao", "dorada",
      "lubina", "filete", "costillas", "pechuga", "muslo", "muslos", "alitas",
      "contramuslo", "cordero", "conejo", "pato", "codorniz", "chorizo",
      "salchichon", "salchichón", "fuet", "morcilla", "butifarra", "longaniza",
      "panceta", "tocino", "chopped", "mortadela", "york", "jamón york",
      "jamon york", "jamón serrano", "jamon serrano", "paleta", "lacon", "lacón",
      "embutido", "embutidos", "fiambre", "carne picada", "picada", "albondigas",
      "albóndigas", "solomillo", "entrecot", "secreto", "presa", "magret",
      "rabo", "morcillo", "osobuco", "cinta de lomo", "sepia", "calamar",
      "pulpo", "mejillon", "mejillón", "almeja", "almejas", "vieira", "rape",
      "rodaballo", "lenguado", "sardina", "sardinas", "boqueron", "boquerón",
      "boquerones", "caballa", "trucha", "pez espada", "emperador", "bonito",
      "gallo", "sepia", "chipiron", "chipirón", "chipirones", "surimi", "gulas",
      "marisco", "mariscos", "cigala", "cigalas", "nécora", "necora", "centollo",
      "bogavante", "langosta", "tartar", "salmón ahumado", "ahumado", "ahumados",
      "lomo embuchado", "cecina", "hígado", "higado",
    ]),
    #("🥖 Panadería", [
      "pan", "tostada", "tostadas", "croissant", "croissants", "bollo", "bollos",
      "magdalena", "magdalenas", "baguette", "harina", "bizcocho", "barra",
      "picos", "pan de molde", "pan integral", "pan rallado", "panecillo",
      "panecillos", "bocadillo", "pan de hamburguesa", "pan de perrito",
      "pan bimbo", "bimbo", "pan tostado", "biscotes", "regañá", "regana",
      "colines", "rosquilletas", "chapata", "ciabatta", "pita",
      "tortilla de trigo", "tortillas de trigo", "wrap", "wraps",
      "tortilla mexicana", "masa", "masa de hojaldre", "masa quebrada",
      "empanada", "empanadas", "hogaza", "pan de centeno", "pan sin gluten",
      "coca de", "roscón", "roscon", "torrijas", "pan de pasas",
    ]),
    #("🥬 Frutas y verduras", [
      "manzana", "platano", "plátano", "naranja", "pera", "limon", "limón",
      "aguacate", "tomate", "lechuga", "cebolla", "patata", "zanahoria",
      "calabacin", "calabacín", "pimiento", "ajo", "fresa", "uva", "melon",
      "melón", "sandia", "sandía", "espinaca", "brocoli", "brócoli", "champiñon",
      "champiñón", "seta", "kiwi", "mandarina", "pepino", "puerro", "verdura",
      "fruta", "cereza", "calabaza", "fresas", "tomates", "patatas", "berenjena",
      "coliflor", "col", "repollo", "lombarda", "acelga", "acelgas",
      "judia verde", "judía verde", "judias verdes", "judías verdes",
      "guisantes", "habas", "esparrago", "espárrago", "esparragos", "espárragos",
      "alcachofa", "alcachofas", "apio", "remolacha", "rabano", "rábano", "nabo",
      "boniato", "batata", "chirivia", "chirivía", "endivia", "endivias",
      "escarola", "rucula", "rúcula", "canonigos", "canónigos", "brotes",
      "ensalada", "bolsa de ensalada", "cebolleta", "cebollino", "chalota",
      "chalotas", "perejil", "cilantro", "albahaca", "menta", "hierbabuena",
      "eneldo", "jengibre", "guindilla", "chile", "jalapeño", "jalapeno",
      "pimiento rojo", "pimiento verde", "pimientos", "tomate cherry",
      "tomate pera", "tomate rama", "tomate de ensalada", "limones", "limas",
      "lima", "pomelo", "clementina", "clementinas", "mandarinas", "naranjas",
      "manzanas", "peras", "platanos", "plátanos", "banana", "bananas",
      "melocoton", "melocotón", "nectarina", "albaricoque", "ciruela",
      "ciruelas", "cerezas", "higo", "higos", "granada", "caqui", "chirimoya",
      "mango", "papaya", "piña", "pina", "coco", "maracuya", "maracuyá", "lichi",
      "frambuesa", "frambuesas", "arandanos", "arándanos", "mora", "moras",
      "grosella", "melones", "sandias", "sandías", "uvas", "membrillo fresco",
      "dátil fresco", "champiñones", "setas", "shiitake", "portobello",
      "boletus", "trufa", "maiz fresco", "maíz fresco", "mazorca", "rabanitos",
      "zanahorias", "cebollas", "ajos", "calabacines", "berenjenas", "pepinos",
      "puerros", "aguacates", "hortaliza", "hortalizas", "fruta de temporada",
      "frutas", "verduras", "macedonia", "sofrito fresco", "guacamole", "hummus",
    ]),
    #("🏠 Hogar y bazar", [
      "pila", "pilas", "bombilla", "bombillas", "vela", "velas", "cerillas",
      "mechero", "encendedor", "pegamento", "cinta adhesiva", "celo", "tijeras",
      "boligrafo", "bolígrafo", "cuaderno", "folios", "sobre", "sobres",
      "percha", "perchas", "pinzas", "tendedero", "plancha", "sarten", "sartén",
      "olla", "cazuela", "cubiertos", "vaso", "vasos", "plato", "platos", "taza",
      "tazas", "tupper", "tuppers", "fiambrera", "botella reutilizable", "termo",
      "sabana", "sábana", "toalla", "toallas", "manta", "almohada", "cortina",
      "alargador", "regleta", "enchufe", "cable", "cargador", "usb", "bateria",
      "batería", "destornillador", "martillo", "clavos", "tornillos", "taladro",
      "brocha", "pintura", "maceta", "tierra", "abono", "semillas", "flores",
      "planta", "plantas", "calcetines", "calzoncillos", "camiseta", "ropa",
      "zapatillas", "bolsa",
    ]),
  ]

  let words =
    lower
    |> string.split(" ")
    |> list.map(string.trim)

  rules
  |> list.find_map(fn(rule) {
    let #(category, keywords) = rule
    case contains_any(words, lower, keywords) {
      True -> Ok(category)
      False -> Error(Nil)
    }
  })
  |> result.unwrap("📦 Otros")
}

fn contains_any(
  words: List(String),
  full_text: String,
  keywords: List(String),
) -> Bool {
  list.any(keywords, fn(kw) {
    let kw_lower = string.lowercase(kw)
    case string.contains(kw_lower, " ") {
      True -> string.contains(full_text, kw_lower)
      False ->
        case string.length(kw_lower) <= 4 {
          True ->
            list.any(words, fn(w) {
              w == kw_lower || w == kw_lower <> "s" || w == kw_lower <> "es"
            })
          False -> string.contains(full_text, kw_lower)
        }
    }
  })
}
